### ISSUE TITLE
Locales not loading when deployed to mobile device

### ISSUE THREAD

**Issue by GabLeRoux** [camsjams/i18n-unity-csharp#1]
Hey there, nice tool btw :), I can't believe Unity does so much and doesn't provide an i18n module with common translation formats. Anyway, thanks for this! :)

I followed instructions and it works in the unity editor, but once deployed to a device, I get 

```
Missing: locale [en-US] not found in supported list. Could not find a part of the path "/Assets/Resources/Locales/en-US.json".
```

Hopefully, it's easy to provide a custom path, I though default `Assets/Resources/Locales` would be ok but it failed so I tried to use something like this:

``` c#
using UnityEngine;
using Mgl;
...
// yes this is ugly ;)
localePath = Application.streamingAssetsPath + "/../../Assets/Resources/Locales/";
I18n.Configure (localePath, defaultLocale, logMissing);
```

But I got a similar error on IOS (did not test on android yet).

```
Missing: locale [en-US] not found in supported list. Could not find a part of the path "/private/var/mobile/Containers/Bundle/Application/xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/application_name.app/Assets/Resources/Locales/en-US.json".
```

Tried with `localePath = Application.dataPath + "/Resources/Locales/";` and result is `/private/var/mobile/Containers/Bundle/Application/xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/application_name.app/Data/Resources/Locales/en-US.json`

I'll try with other ways and post here again if I find something. My translation files are located in `Assets/Resources/Locales/`, as mentioned in the first lines, it works in unity editor ;)

**Comment by camsjams** [comment]
Thanks for using the library!

I've been able to get this to work on Android devices, currently it is being utilized in one of our newly launched games:
https://play.google.com/store/apps/details?id=com.MoonGateLabs.TheTraderFree

I have not been able to test on an iOS device yet (our iPad broke!), only Windows, Mac, and Android phones/tablets.

Are you able to get this working in a desktop application (standalone Windows/Mac)?

Also, is the first usage inside of a `Start()` function? When used inside of `Awake()` it will work in the Editor, but not in a compiled game (I've been meaning to find a way to trigger a warning for this!)

```
void Start()
{
         string hW = i18n.__("Hello World!");
}
```

**Comment by camsjams** [comment]
I should also note, we are using all defaults:

```
private I18n i18n = I18n.Instance;
...
void Start()
{
    string hW = i18n.__("Hello World!");
}
```

**Comment by GabLeRoux** [comment]
Thanks for your quick answer, I probably have some calls in `Awake()` indeed, I'll try what you suggested tonight. Oh and I'll give this game a try :+1:

**Comment by camsjams** [comment]
Ok - I will keep you posted once we have access to another iOS device.

**Comment by GabLeRoux** [comment]
I was running `I18n.Configure` from an `Awake` method, moved this to `Start`, used default path, but it's not showing up on my side, as you mentioned, it works in the unity player. I deployed to unity web player and it fails too. 

I quickly tried to use `(TextAsset) Resources.Load("locale/" + _currentLocale)` instead of `System.IO.StreamReader` directly in the lib (inside `static void InitConfig()`) and I think it's working so I'll be using that untill I find a cleaner way. Sometimes, we have to do it the unity way ;)

I'll be away for a couple of days, but I'll work on this next week.

**Comment by camsjams** [comment]
Hmm that's funny - I recently switched it to use the `TextAsset` method:
https://github.com/MoonGateLabs/i18n-unity-csharp/commit/0be41e208efca92c31c128fba8c76f7a520715e3

I tested current master on the Unity Web Player and didn't see any issues - the translations were loaded correctly.

We are ordering an iPod touch and will be able to test on it soon.

**Comment by GabLeRoux** [comment]
Closing this. It's been a few years now and I did not update here, but I confirm I was able to deploy this correctly to mobile (a while ago). Translations were stored to `./Assets/Resources/Locales/`. Calling translations in `Start` method works and `TextAsset` does load the translation files correctly 👍
